/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SymbolObject } from "./components/dictionary-symbol-browser/dictionary-symbol-browser";
export namespace Components {
    interface DictionarySymbolBrowser {
        "styleurl": string;
        "symbolAttributes": Object;
        "uiurl": string;
    }
}
declare global {
    interface HTMLDictionarySymbolBrowserElement extends Components.DictionarySymbolBrowser, HTMLStencilElement {
    }
    var HTMLDictionarySymbolBrowserElement: {
        prototype: HTMLDictionarySymbolBrowserElement;
        new (): HTMLDictionarySymbolBrowserElement;
    };
    interface HTMLElementTagNameMap {
        "dictionary-symbol-browser": HTMLDictionarySymbolBrowserElement;
    }
}
declare namespace LocalJSX {
    interface DictionarySymbolBrowser {
        "onSymbolChanged"?: (event: CustomEvent<SymbolObject>) => void;
        "styleurl"?: string;
        "symbolAttributes"?: Object;
        "uiurl"?: string;
    }
    interface IntrinsicElements {
        "dictionary-symbol-browser": DictionarySymbolBrowser;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dictionary-symbol-browser": LocalJSX.DictionarySymbolBrowser & JSXBase.HTMLAttributes<HTMLDictionarySymbolBrowserElement>;
        }
    }
}
